/******************************************************************************
 *
 * A P E X 2 E B S
 * Copyright (C) 2016 Christopher Ho / SymbolThree
 * All Rights Reserved, http://www.symbolthree.com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * E-mail: christopher.ho@symbolthree.com
 *
 * ================================================
 *
 * $Archive: /TOOL/APEX2EBS/APEX/SQL/A2E_LANG_MAPPING_DATA.sql $
 * $Author: Christopher Ho $
 * $Date: 6/20/16 7:06a $
 * $Revision: 4 $
 ******************************************************************************/
 
SET DEFINE OFF;
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Afrikaans','af','af','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Standard)','ar','ar','AR','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (U.A.E.)','ar-ae','ar-ae','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Bahrain)','ar-bh','ar-bh','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Algeria)','ar-dz','ar-dz','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Egypt)','ar-eg','ar-eg','EG','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Iraq)','ar-iq','ar-iq','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Jordan)','ar-jo','ar-jo','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Kuwait)','ar-kw','ar-kw','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Lebanon)','ar-lb','ar-lb','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Libya)','ar-ly','ar-ly','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Morocco)','ar-ma','ar-ma','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Oman)','ar-om','ar-om','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Qatar)','ar-qa','ar-qa','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Saudi Arabia)','ar-sa','ar-sa','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Syria)','ar-sy','ar-sy','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Tunisia)','ar-tn','ar-tn','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Arabic (Yemen)','ar-ye','ar-ye','AR','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Assamese','as','as',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Asturian','ast',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Azerbaijani','az',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Belarusian','be','be',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Bulgarian','bg','bg','BG','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Bengali','bn','bn',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Breton','br',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Bosnian','bs',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Catalan','ca','ca','CA','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chechen','ce',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chamorro','ch',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Corsican','co',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Cree','cr',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Czech','cs','cs','CS','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chuvash','cv',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Welsh','cy','cy',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Danish','da','da','DK','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('German (Standard)','de','de','D','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('German (Austria)','de-at','de-at','D','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('German (Switzerland)','de-ch','de-ch','D','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('German (Germany)','de-de','de','D','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('German (Liechtenstein)','de-li','de-li','D','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('German (Luxembourg)','de-lu','de-lu','D','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Greek','el','el','EL','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English','en','en','US','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Australia)','en-au','en-au','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Belize)','en-bz','en-bz','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Canada)','en-ca','en-ca','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (United Kingdom)','en-gb','en-gb','GB','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Ireland)','en-ie','en-ie','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Jamaica)','en-jm','en-jm','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (New Zealand)','en-nz','en-nz','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Philippines)','en-ph','en-ph','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Trinidad & Tobago)','en-tt','en-tt','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (United States)','en-us','en-us','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (South Africa)','en-za','en-za','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('English (Zimbabwe)','en-zw','en-zw','US','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Esperanto','eo',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish','es','es','E','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Argentina)','es-ar','es-ar','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Bolivia)','es-bo','es-bo','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Chile)','es-cl','es-cl','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Colombia)','es-co','es-co','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Costa Rica)','es-cr','es-cr','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Dominican Republic)','es-do','es-do','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Ecuador)','es-ec','es-ec','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Spain)','es-es','es-es','E','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (US)','es-us','es-us','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Guatemala)','es-gt','es-gt','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Honduras)','es-hn','es-hn','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Mexico)','es-mx','es-mx','ESA','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Nicaragua)','es-ni','es-ni','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Panama)','es-pa','es-pa','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Peru)','es-pe','es-pe','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Puerto Rico)','es-pr','es-pr','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Paraguay)','es-py','es-py','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (El Salvador)','es-sv','es-sv','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Uruguay)','es-uy','es-uy','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Spanish (Venezuela)','es-ve','es-ve','ESA','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Estonian','et','et',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Basque','eu','eu',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Farsi / Persian','fa','fa',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Persian/Iran','fa-ir','fa',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Finnish','fi','fi','SF','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Fijian','fj',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Faeroese','fo','fo',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('French (Standard)','fr','fr','F','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('French (Belgium)','fr-be','fr-be','F','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('French (Canada)','fr-ca','fr-ca','FRC','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('French (Switzerland)','fr-ch','fr-ch','F','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('French (France)','fr-fr','fr','F','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('French (Luxembourg)','fr-lu','fr-lu','F','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('French (Monaco)','fr-mc','fr-mc','F','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Friulian','fur',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Frisian','fy',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Irish','ga','ga',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Gaelic (Scots)','gd','gd',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Gaelic (Irish)','gd-ie',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Galacian','gl','gl',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Gujurati','gu','gu',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Hebrew','he','he','IW','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Hindi','hi','hi',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Croatian','hr','hr','HR','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Upper Sorbian','hsb',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Haitian','ht',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Hungarian','hu','hu','HU','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Armenian','hy','hy',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Indonesian','id','id','IN','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Icelandic','is','is','IS','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Italian (Standard)','it','it','I','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Italian (Switzerland)','it-ch','it-ch','I','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Inuktitut','iu',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Japanese','ja','ja','JA','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Yiddish','ji',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Georgian','ka',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Kazakh','kk','kk',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Khmer','km',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Kannada','kn','kn',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Korean','ko','ko','KO','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Korean (North Korea)','ko-kp','ko','KO','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Korean (South Korea)','ko-kr','ko','KO','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Konkani','kok','kok',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Kyrgyz','kz','kz',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Kashmiri','ks',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Kirghiz','ky',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Latin','la',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Luxembourgish','lb',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Lithuanian','lt','lt','LT','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Latvian','lv','lv',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Maori','mi',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('FYRO Macedonian','mk','mk',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Malayalam','ml','ml',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Moldavian','mo',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Marathi','mr','mr',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Malay','ms','ms',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Maltese','mt','mt',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Burmese','my',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Norwegian (Bokmal)','nb','nb-no','N','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Nepali','ne','ne',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Ndonga','ng',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Dutch (Standard)','nl','nl','NL','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Dutch (Belgian)','nl-be','nl-be','NL','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Norwegian (Nynorsk)','nn','nn-no','N','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Norwegian','no','no','N','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Navajo','nv',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Occitan','oc',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Oromo','om',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Oriya','or','or',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Punjabi','pa','pa',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Punjabi (India)','pa-in','pa',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Punjabi (Pakistan)','pa-pk','pa',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Polish','pl','pl','PL','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Portuguese','pt','pt','PT','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Portuguese (Brazil)','pt-br','pt-br','PTB','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Quechua','qu',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Rhaeto-Romanic','rm',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Romanian','ro','ro','RO','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Romanian (Moldavia)','ro-mo','ro','RO','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Russian','ru','ru','RU','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Russian (Moldavia)','ru-mo','ru-md','RU','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Sanskrit','sa',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Sorbian','sb',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Sardinian','sc',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Sindhi','sd',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Sango','sg',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Singhalese','si',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Slovak','sk','sk','SK','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Slovenian','sl','sl','SL','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Somani','so',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Albanian','sq','sq','SQ','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Serbian','sr','sr',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Swedish','sv','sv','S','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Swedish (Finland)','sv-fi','sv-fi','S','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Swedish (Sweden)','sv-sv','sv-fi','S','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Swahili','sw',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Sutu','sx',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Sami (Lappish)','sz',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Tamil','ta','ta',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Teluga','te','te',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Thai','th','th','TH','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Tigre','tig',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Turkmen','tk',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Klingon','tlh',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Tswana','tn',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Turkish','tr','tr','TR','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Tsonga','ts',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Tatar','tt',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Ukrainian','uk','uk','UK','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Urdu','ur','ur',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Uzbek','uz','uz',null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Venda','ve',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Vietnamese','vi','vi','VN','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Volapuk','vo',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Walloon','wa',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Xhosa','xh',null,null,null);
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chinese','zh','zh','ZHS','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chinese (PRC)','zh-cn','zh-cn','ZHS','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chinese (Hong Kong)','zh-hk','zh-hk','ZHT','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chinese (Macau SAR)','zh-mo','zh-mo','ZHT','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chinese (Singapore)','zh-sg','zh-sg','ZHS','N');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Chinese (Taiwan)','zh-tw','zh-tw','ZHT','Y');
Insert into A2E_LANG_MAPPING (DISPLAY_NAME,HTTP_ACCEPT_LANGUAGE,FSP_LANGUAGE_PREFERENCE,EBS_LANG,DEFAULT_MAPPING) values ('Zulu','zu',null,null,null);
commit;